version: '3.8'

services:
  saree-mysql:
    image: mysql:8.0
    container_name: saree-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saree_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  saree-catalog-service:
    build:
      context: ./saree-catalog-service
      dockerfile: Dockerfile
    container_name: saree-catalog-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://saree-mysql:3306/saree_db?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - saree-mysql

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://saree-mysql:3306/saree_db?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - saree-mysql

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://saree-mysql:3306/saree_db?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - saree-mysql

volumes:
  mysql_data:
